# Benchy Configuration File Example
# Copy this file to 'benchy.toml' and customize for your project

# Global settings that apply to all commands (top-level properties)
verbose = false
output_directory = "./benchmark-results"
output_style = ["console"]
significance_threshold = 0.05  # 5% threshold for significant changes
benchmarks = [
    "MyProject.Benchmarks",
    "MyProject.PerformanceTests",
]

# Interactive mode specific settings
[interactive]
# Override global settings for interactive mode
output_style = ["console"]
no_delete = false
benchmarks = [
    "MyProject.Benchmarks",
    "MyProject.PerformanceTests",
    "MyProject.InteractiveBenchmarks",
]

# CI mode specific settings
[ci]
# Override global settings for CI mode
output_style = ["json", "markdown"]
verbose = true
significance_threshold = 0.03  # Stricter 3% threshold for CI
benchmarks = [
    "MyProject.Benchmarks",
    "MyProject.StabilityTests",
    "MyProject.RegressionTests",
]
