name: Publish NuGet Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract version from tag
      id: version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Tag name: $TAG_NAME"
        
        VERSION=${TAG_NAME#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --no-restore
      
    - name: Test project
      run: dotnet test --configuration Release --no-build --verbosity normal
      continue-on-error: false
      
    - name: Pack NuGet package
      run: dotnet pack Benchy/Benchy.csproj -p:PackageVersion=${{ steps.version.outputs.version }} --configuration Release --no-build --output ./nupkg

    - name: List generated packages
      run: ls -la ./nupkg/
      
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate